/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export default function Square(props) {
  const { nodes, materials } = useGLTF("/scene.glb");
  return (
    <group {...props} dispose={null}>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Escaleras001.geometry}
          material={nodes.Escaleras001.material}
          position={[-0.936, -0.535, 0.017]}
          scale={[0.858, 0.858, 0.927]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Kiosko.geometry}
          material={materials["Material.004"]}
          position={[-0.478, 0.035, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Kiosko001.geometry}
          material={materials["Material.004"]}
          position={[-24.395, 0.045, -2.285]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Kiosko002.geometry}
          material={materials["Material.004"]}
          position={[71.883, 0.035, 0]}
        />
        <group position={[72.361, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube011.geometry}
            material={materials.Material}
            position={[-1.362, 0.308, 0.079]}
            scale={[0.774, 0.836, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube012.geometry}
            material={materials["Material.001"]}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube013.geometry}
            material={materials["Material.001"]}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube014.geometry}
            material={materials["Material.001"]}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube015.geometry}
            material={materials["Material.001"]}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube016.geometry}
            material={materials["Material.001"]}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube017.geometry}
            material={materials["Material.001"]}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube018.geometry}
            material={materials["Material.003"]}
            position={[0.162, 0.194, 0.079]}
            scale={[0.774, 0.836, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere006.geometry}
            material={materials.Material}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere007.geometry}
            material={materials.Material}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere008.geometry}
            material={materials.Material}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009.geometry}
            material={materials.Material}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere010.geometry}
            material={materials.Material}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere011.geometry}
            material={materials.Material}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Kiosko003.geometry}
          material={materials["Material.004"]}
          position={[47.966, 0.045, -2.285]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Kiosko004.geometry}
          material={materials["Material.004"]}
          position={[-66.64, 0.035, 0]}
        />
        <group position={[-66.162, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube020.geometry}
            material={materials.Material}
            position={[-1.362, 0.308, 0.079]}
            scale={[0.774, 0.836, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube021.geometry}
            material={materials["Material.001"]}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube022.geometry}
            material={materials["Material.001"]}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube023.geometry}
            material={materials["Material.001"]}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube024.geometry}
            material={materials["Material.001"]}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube025.geometry}
            material={materials["Material.001"]}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube026.geometry}
            material={materials["Material.001"]}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube027.geometry}
            material={materials["Material.003"]}
            position={[0.162, 0.194, 0.079]}
            scale={[0.774, 0.836, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere012.geometry}
            material={materials.Material}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere013.geometry}
            material={materials.Material}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere014.geometry}
            material={materials.Material}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere015.geometry}
            material={materials.Material}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere016.geometry}
            material={materials.Material}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere017.geometry}
            material={materials.Material}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Kiosko005.geometry}
          material={materials["Material.004"]}
          position={[-90.557, 0.045, -2.285]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Kiosko006.geometry}
          material={materials["Material.004"]}
          position={[-0.478, 0.035, -41.361]}
        />
        <group position={[0, 0, -41.361]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube029.geometry}
            material={materials.Material}
            position={[-1.362, 0.308, 0.079]}
            scale={[0.774, 0.836, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube030.geometry}
            material={materials["Material.001"]}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube031.geometry}
            material={materials["Material.001"]}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube032.geometry}
            material={materials["Material.001"]}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube033.geometry}
            material={materials["Material.001"]}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube034.geometry}
            material={materials["Material.001"]}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube035.geometry}
            material={materials["Material.001"]}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube036.geometry}
            material={materials["Material.003"]}
            position={[0.162, 0.194, 0.079]}
            scale={[0.774, 0.836, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere018.geometry}
            material={materials.Material}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere019.geometry}
            material={materials.Material}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere020.geometry}
            material={materials.Material}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere021.geometry}
            material={materials.Material}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere022.geometry}
            material={materials.Material}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere023.geometry}
            material={materials.Material}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Kiosko007.geometry}
          material={materials["Material.004"]}
          position={[-24.395, 0.045, -43.645]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Kiosko008.geometry}
          material={materials["Material.004"]}
          position={[-0.478, 0.035, 42.351]}
        />
        <group position={[0, 0, 42.351]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube038.geometry}
            material={materials.Material}
            position={[-1.362, 0.308, 0.079]}
            scale={[0.774, 0.836, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube039.geometry}
            material={materials["Material.001"]}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube040.geometry}
            material={materials["Material.001"]}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube041.geometry}
            material={materials["Material.001"]}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube042.geometry}
            material={materials["Material.001"]}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube043.geometry}
            material={materials["Material.001"]}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube044.geometry}
            material={materials["Material.001"]}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube045.geometry}
            material={materials["Material.003"]}
            position={[0.162, 0.194, 0.079]}
            scale={[0.774, 0.836, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere024.geometry}
            material={materials.Material}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere025.geometry}
            material={materials.Material}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere026.geometry}
            material={materials.Material}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere027.geometry}
            material={materials.Material}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere028.geometry}
            material={materials.Material}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere029.geometry}
            material={materials.Material}
            position={[0.162, -0.375, 0.079]}
            scale={[0.774, 1.13, 0.785]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Kiosko009.geometry}
          material={materials["Material.004"]}
          position={[-24.395, 0.045, 40.067]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials["Dark Brown Marble"]}
        />
        <group position={[72.361, 0.011, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane001.geometry}
            material={materials.Cement}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane001_1.geometry}
            material={materials["Material.005"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010.geometry}
          material={materials["Dark Brown Marble"]}
          position={[72.361, 0, 0]}
        />
        <group position={[72.361, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh002.geometry}
            material={materials["Dark Brown Marble"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh004.geometry}
            material={materials["Dark Brown Marble"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh005.geometry}
            material={materials["Dark Brown Marble"]}
          />
        </group>
        <group position={[-66.162, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane002.geometry}
            material={materials.Cement}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane002_1.geometry}
            material={materials["Material.005"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019.geometry}
          material={materials["Dark Brown Marble"]}
          position={[-66.162, 0, 0]}
        />
        <group position={[-66.162, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh006.geometry}
            material={materials["Dark Brown Marble"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh007.geometry}
            material={materials["Dark Brown Marble"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh008.geometry}
            material={materials["Dark Brown Marble"]}
          />
        </group>
        <group position={[0, 0, -41.361]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane003.geometry}
            material={materials.Cement}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane003_1.geometry}
            material={materials["Material.005"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028.geometry}
          material={materials["Dark Brown Marble"]}
          position={[0, 0, -41.361]}
        />
        <group position={[0, 0, -41.361]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009.geometry}
            material={materials["Dark Brown Marble"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh010.geometry}
            material={materials["Dark Brown Marble"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh011.geometry}
            material={materials["Dark Brown Marble"]}
          />
        </group>
        <group position={[0, 0, 42.351]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane004.geometry}
            material={materials.Cement}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane004_1.geometry}
            material={materials["Material.005"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube037.geometry}
          material={materials["Dark Brown Marble"]}
          position={[0, 0, 42.351]}
        />
        <group position={[0, 0, 42.351]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh012.geometry}
            material={materials["Dark Brown Marble"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh013.geometry}
            material={materials["Dark Brown Marble"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh014.geometry}
            material={materials["Dark Brown Marble"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials.Material}
          position={[-1.362, 0.308, 0.079]}
          scale={[0.774, 0.836, 0.785]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={materials["Material.001"]}
          position={[0.162, -0.375, 0.079]}
          scale={[0.774, 1.13, 0.785]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials["Material.001"]}
          position={[0.162, -0.375, 0.079]}
          scale={[0.774, 1.13, 0.785]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={materials["Material.001"]}
          position={[0.162, -0.375, 0.079]}
          scale={[0.774, 1.13, 0.785]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={materials["Material.001"]}
          position={[0.162, -0.375, 0.079]}
          scale={[0.774, 1.13, 0.785]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007.geometry}
          material={materials["Material.001"]}
          position={[0.162, -0.375, 0.079]}
          scale={[0.774, 1.13, 0.785]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008.geometry}
          material={materials["Material.001"]}
          position={[0.162, -0.375, 0.079]}
          scale={[0.774, 1.13, 0.785]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009.geometry}
          material={materials["Material.003"]}
          position={[0.162, 0.194, 0.079]}
          scale={[0.774, 0.836, 0.785]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere.geometry}
          material={materials.Material}
          position={[0.162, -0.375, 0.079]}
          scale={[0.774, 1.13, 0.785]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere001.geometry}
          material={materials.Material}
          position={[0.162, -0.375, 0.079]}
          scale={[0.774, 1.13, 0.785]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere002.geometry}
          material={materials.Material}
          position={[0.162, -0.375, 0.079]}
          scale={[0.774, 1.13, 0.785]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere003.geometry}
          material={materials.Material}
          position={[0.162, -0.375, 0.079]}
          scale={[0.774, 1.13, 0.785]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere004.geometry}
          material={materials.Material}
          position={[0.162, -0.375, 0.079]}
          scale={[0.774, 1.13, 0.785]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere005.geometry}
          material={materials.Material}
          position={[0.162, -0.375, 0.079]}
          scale={[0.774, 1.13, 0.785]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials.Cement}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh.geometry}
          material={materials["Dark Brown Marble"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001.geometry}
          material={materials["Dark Brown Marble"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh003.geometry}
          material={materials["Dark Brown Marble"]}
        />
      </RigidBody>
    </group>
  );
}

useGLTF.preload("/scene.glb");
